# Numpy -- Manipulation  
We can index through single-dimensioned numpy arrays the same way as with lists, using square brackets

In [1]:
import numpy as np 
my_array = np.array([1, 6, 3, 4])
print(my_array[0])
print(my_array[2])

1
3


More dimensions is different. Numpy arrays handle multiple dimensions in a single structure, rather than nesting lists inside of lists. We access the items in a 2d array using `[row, column]`

In [ ]:
my_matrix = np.zeros((3, 4))
my_matrix[0, 0] = 1
print(my_matrix)

The list slicing operations work with numpy arrays as well, but now we can specify the step as well.

In [2]:
arr = np.array([1, 1, 2, 3, 5, 8, 13])
first_half = arr[0:4]
print(first_half)

[ 1  2  5 13]


We can omit any of the three parameters, and python will default to [0:arr.size:1] for any ommitted parameter.

In [3]:
evens = arr[0::2]
print(evens)

[1 1 2 3]


We can modify slices of an array using another array of the same size. This cannot be done with lists

In [5]:
arr[0:3] = np.array([0, 0, 0])
print(arr)

[ 0  0  0  3  5  8 13]


Slicing works the same way in multiple dimensions

In [6]:
arr_2d = np.zeros((3,4))
print(arr_2d)
arr_row_1 = arr_2d[1, :]
print(arr_row_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]


One of the most useful reasons to use numpy arrays is how they handle **math**. Lets think about how we add 1 to each element of a list.

In [ ]:
lis = [0, 1, 2, 3]
lis[0] = lis[0] + 1
lis[1] = lis[1] + 1
lis[2] = lis[2] + 1
lis[3] = lis[3] + 1
print(lis)

With numpy arrays, we simply add 1 to the array

In [7]:
np_arr = np.array([0, 1, 2, 3])
np_arr = np_arr + 1
print(np_arr)

[1 2 3 4]


We can do the exact same thing for multiplication

In [8]:
np_arr = np_arr * 2
print(np_arr)

[2 4 6 8]


We can also add, subtract, multiply and divide numpy arrays element by element.

In [9]:
arr1 = np.ones(5)
arr2 = np.arange(0, 5)
arr3 = arr1 + arr2
print(arr3)

[1. 2. 3. 4. 5.]


In [10]:
arr4 = arr3 * arr2
print(arr4)

[ 0.  2.  6. 12. 20.]


In [12]:
arr5 = arr4 / arr3
print(arr5)

[0. 1. 2. 3. 4.]
