# Lesson 7: 
# Array datatype using "Numpy" 

## Array datatype

We just finished a lesson on **Lists**. 

Now we are learning about a new datatype called an **Array**. Arrays are like **Lists** with 2 main differences:  
1. Arrays are of fixed size. Lists can change in size as we go on.  
2. All the elements in an Array have to be the same datatype. You can have different datatypes within a list.  
  
**DEMO**  
  
Why do you think an **Array** would be a useful datatype?  
  
Have you seen an **Array** in math? Think about Google sheets, Excel, Rubics cube... These are all higher dimensional arrays. 

## What is numpy?

The `numpy` **module** is used in almost all large scale math computation using Python. We will be using this package instead of `math`.

https://numpy.org/doc/stable/user/basics.creation.html is a good source.

It is a package(code written by others) that provide high-performance vector, matrix and even higher-dimensional data structures for Python. In other words **higher level math operations becomes super easy if we use numpy's various functions**. Underneath the hood, numpy is implemented in C and Fortran so the performance is very good. That means it is fast!!

To use `numpy` you need to import the module, or a specific **function** inside a module.

In [1]:
import numpy as np

This tells python to import the `numpy` module, and to use the `np` abbreviation to refer to it in code. You are free to use any abbreviation, but `np` is standard.

**The main datatype we will use from Numpy is the array.**  
We can intialize these arrays with a few functions.  
* using functions dedicated to creating numpy arrays, such as `arange` and `linspace`
* using `zeros` to initialize the array to all zeros  
* using `ones` to initialize the array to all ones
* using `array` to initialize the array from a list

## Methods to create a numpy Array

The most common way to create a numpy array is to set all the values to zero. This is done with the `zeros` function

In [2]:
my_array = np.zeros(5) #The array is 5 elements long
print(my_array)

[0. 0. 0. 0. 0.]


The `zeros()` function takes an integer that determines the length of the numpy array, or how many elements it holds.  
Alternatively, you can give it a tuple, which will determine its shape.

In [3]:
my_matrix = np.zeros((3, 4)) #(number of rows, number of columns)
print(my_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Exercise 1: Create an array and a matrix

1. Write the code to generate an array named one_array = `[1. 1. 1. 1. 1. 1.]`
2. Write the code to generate a 2 dimensional matrix 
   <br> one_matrix = 
   <br>`[[1.1.1.1.]`
   <br>`[1.1.1.1.]]`
<br>Hint: Use the `ones()` function


In [11]:
one_array = np.ones(6)
one_matrix = np.ones((2, 4))

## Numpy methods to find the shape and size of an Array

Arrays in numpy have some `methods` that either return properties about the array or manipulate the array  
`shape` tells us the shape of the array, as (rows, columns)  
`size` tells us the total number of elements in the array  

In [4]:
my_array_size = my_array.size
my_array_shape = my_array.shape 
print(my_array_size)
print(my_array_shape)

5
(5,)


Alternatively, we can use numpy `functions` that take in a numpy array as input, and output the shape and size

In [5]:
my_matrix_size = np.size(my_matrix)
my_matrix_shape = np.shape(my_matrix)
print(my_matrix_size)
print(my_matrix_shape)

12
(3, 4)


## Numpy method to find the datatype in the Array

We can find the array's type using `dtype`

In [6]:
my_array.dtype

dtype('float64')

Notice that the type is `float64`. This is the default type of a numpy array. It is a type of `float` on a 64 bit machine. We generally don't have to worry about the bit sizes on modern computers, for our purposes this is a `float`

`numpy` has an `array` function to allow us to specify information about the array.
<br>
For example, lets turn `my_array` into an array of integers

In [7]:
int_array = np.array(my_array, dtype = 'int') 

We can also use the `array` function to convert **lists** into numpy arrays.

In [8]:
# Example 1 of creating a numpy array from a list
flt_array2 = np.array([1, 2, 2, 1], dtype = 'float')

We use the `dtype` keyword argument to specify what type we want. Now we can check the type of `int_array`

In [9]:
print (int_array)
print(int_array.dtype)
print ("flt_array2 =", flt_array2)
print (flt_array2.dtype)

[0 0 0 0 0]
int64
flt_array2 = [1. 2. 2. 1.]
float64


In [10]:
#Example 2 of creating an numpy array from a list
lis = [1, 2, 3]
converted_array = np.array(lis)
print(converted_array)
print (converted_array.dtype)

[1 2 3]
int64


### Exercise 2: Create an array that holds your phone number  
  
Create an array using the `array()` method to hold your 10 digit phone number.  
You must decide what the datatype should be. Remember the default is always float.  
1. Create the array  
2. Find the `dtype` of the array elements  
3. Find the `size()` of the array  
4. Find the `shape()` of the array  

In [13]:
arr = np.array([9, 4, 9, 4, 6, 8, 7, 7, 6, 4])
print(arr.dtype)

int64


## Numpy array common datatypes

The most common data types in a numpy array are:
* `int` - integer
* `float` - decimal
* `bool` - a type that can store either True or False

### Exercise 3: 

Create a 2 dimensional matrix with the data given below. 
<table>
<tr>
    <th>Grade</th>
    <th>HaveCellPhone</th>
    <th>NoCellPhone</th>
</tr>
<tr>
    <td>7th</td>
    <td>129</td> 
    <td>294</td>
</tr>
<tr>
    <td>8th</td>
    <td>325</td>
    <td>92</td>
</tr>
</table>

When you print out the array it should look like this:
<br>`[[129.  294.]`
<br> `[325.  92. ]]`
 
Find the datatype of the matrix you have created.
Find the size and shape of the matrix you have created


In [16]:
data_arr = np.array([[129, 294], [325, 92]], dtype = 'float')
print(data_arr)

[[129. 294.]
 [325.  92.]]


## Numpy array creation using `arange()` and `linspace()`

Lets look at some more array-generation functions.  
`arange` creates an array of evenly spaced items in a range

In [17]:
ranged_array = np.arange(0, 10, 1) #(starting element included, ending element excluded, stepsize)
print(ranged_array)

[0 1 2 3 4 5 6 7 8 9]


The first argument, or input, for `arange` is the beginning of the range.  This is included in the array.   
The second argument is the end of the range, but it is not included in the range   
The third argument is the step size. 1 means every integer in the range, 2 means every other integer, and so on.

In [18]:
ranged_floats = np.arange(0, 3.2, 0.4)
print(ranged_floats)

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8]


The arguments do not have to be integers, they can be floats as well

`linspace` is very similar to `arange`, but it includes both end points, and the third argument is the amount of elements, not the step.

In [19]:
linspace_array = np.linspace(0, 10, 5) #(starting element included, ending element included, number of elements in array)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


### Exercise 4:  
  
Create an array with numbers ranging from 0 to 15 (including 15) with a stepping interval of 0.5.  
*HINT*: Use `arange()` to create your array.  
How many entries will this array have? Use the `size()` function to find out.

In [23]:
range_arr = np.arange(0, 15.5, 0.5)
print(range_arr)
print(np.size(range_arr))

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15. ]
31
