# Lesson 7: 
# Array datatype using "Numpy" 

## Array datatype

Earlier we used an *import math* statement to do some interesting math operations such as squareroot and factorial. 

We also just finished a lesson on *Lists*. 

Now we are learning about a new datatype called an **Array**. Arrays are like *Lists* with 2 main differences:
1. Arrays are of fixed size. Lists can change in size as we go on.
2. All the elements in an Array have to be the same datatype. You can have different datatypes within a list. 

**DEMO**

Why do you think an **Array** would be a useful datatype?

Have you seen an **Array** in math? Think about Google sheets, Excel, Rubics cube... These are all higher dimensional arrays. 

## What is numpy?

The `numpy` **module** is used in almost all large scale math computation using Python. We will be using this package instead of `math`.

https://numpy.org/doc/stable/user/basics.creation.html is a good source.

It is a package(code written by others) that provide high-performance vector, matrix and even higher-dimensional data structures for Python. In other words **higher level math operations becomes super easy if we use numpy's various functions**. Underneath the hood, numpy is implemented in C and Fortran so the performance is very good. That means it is fast!!

To use `numpy` you need to import the module, or a specific **function** inside a module.

In [1]:
import numpy as np

This tells python to import the `numpy` module, and to use the `np` abbreviation to refer to it in code. You are free to use any abbreviation, but `np` is standard.

**The main datatype we will use from Numpy is the array.**  
We can intialize these arrays with a few functions.  
* using functions dedicated to creating numpy arrays, such as `arange` and `linspace`
* using `zeros` to initialize the array to all zeros  
* using `ones` to initialize the array to all ones
* using `array` to initialize the array from a list

## Steps to create a numpy Array

1. import numpy as np #At the top of your file. 
2. Initialize the array

The most common way to initialize a numpy array is to set all the values to zero. This is done with the `zeros` function

In [2]:
my_array = np.zeros(5) #The array is 5 elements long
print(my_array)

[0. 0. 0. 0. 0.]


The `zeros()` function takes an integer that determines the length of the numpy array, or how many elements it holds.  
Alternatively, you can give it a tuple, which will determine its shape.

In [3]:
my_matrix = np.zeros((3, 4)) #(number of rows, number of columns)
print(my_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Exercise 1: Create an array and a matrix

1. Write the code to generate an array named one_array = [1. 1. 1. 1. 1. 1.]
2. Write the code to generate a 2 dimensional matrix 
    one_matrix = [[1.1.1.1.]
                  [1.1.1.1.]]
Hint: Use the np.ones() function


## Numpy methods to find the shape and size of an Array

Arrays in numpy have some `methods` that either return properties about the array or manipulate the array  
`shape` tells us the shape of the array, as (rows, columns)  
`size` tells us the total number of elements in the array  

In [4]:
my_array_size = my_array.size
my_array_shape = my_array.shape 
print(my_array_size)
print(my_array_shape)

5
(5,)


Alternatively, we can use numpy `functions` that take in a numpy array as input, and output the shape and size

In [5]:
my_matrix_size = np.size(my_matrix)
my_matrix_shape = np.shape(my_matrix)
print(my_matrix_size)
print(my_matrix_shape)

12
(3, 4)


## Numpy method to find the datatype in the Array

We can find the array's type using `dtype`

In [6]:
my_array.dtype

dtype('float64')

Notice that the type is `float64`. This is the default type of a numpy array. It is a type of `float` on a 64 bit machine. We generally don't have to worry about the bit sizes on modern computers, for our purposes this is a `float`

## Numpy's *array* method to create an Array

`numpy` has an `array` function to allow us to specify information about the array  
For example, lets turn that array into an array of integers

In [7]:
int_array = np.array(my_array, dtype = 'int') 
int_array2 = np.array([1, 2, 2, 1], dtype = 'float')

We use the `dtype` keyword argument to specify what type we want. Now we can check the type of `int_array`

In [8]:
print (int_array)
print(int_array.dtype)
print ("int_array2 is =", int_array2)
print (int_array2.dtype)

[0 0 0 0 0]
int32
int_array2 is = [1. 2. 2. 1.]
float64


### Exercise 2: Create an array that holds your phone number

Create an array using the np.array() method to hold your 10 digit phone number. 
You must decide what the datatype should be. Remember the default is always float.
1. Create the array 
2. Find the dtype of the array elements
3. Find the size() of the array
4. Find the shape() of the array

## Numpy array common datatypes

The most common data types in a numpy array are:
* `int` - integer
* `float` - decimal
* `bool` - a type that can store either True or False

## List converted to Numpy Array

We can also use the `array` function to convert lists into numpy arrays

In [9]:
lis = [1, 2, 3]
converted_array = np.array(lis)
print(converted_array)

[1 2 3]


## Numpy array creation using arange() and linspace() 

Lets look at some more array-generation functions.  
`arange` creates an array of evenly spaced items in a range

In [10]:
ranged_array = np.arange(0, 10, 1)
print(ranged_array)

[0 1 2 3 4 5 6 7 8 9]


1. The first argument, or input, for arange is the beginning of the range. 
    This is included in the array.  
2. The second argument is the end of the range, but it is not included 
    in the range  
3. The third argument is the step size. 1 means every integer in the range, 
    2 means every other integer, and so on.

In [11]:
ranged_floats = np.arange(0, 3.2, 0.4)
print(ranged_floats)

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8]


The arguments do not have to be integers, they can be floats as well

`linspace` is very similar to arange, but it includes both end points, and the third argument is the amount of elements, not the step.

In [12]:
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


### Exercise 3: 

Create a 2 dimensional matrix with the data given below. 
Grade    |     HaveCellPhone    |      NoCellPhone
7th      |     129              |      294
8th      |     325              |      92

When you print out the array it should look like this:
[[129.  294.]
 [325.  92. ]]
 
Find the datatype of the matrix you have created.
Find the size and shape of the matrix you have created


### Exercise 4: 

Create an array with numbers ranging from 10 to 35 with a stepping interval of 0.5.HINT: Use arange() to create your array. 
How many entries will this array have? Use the size() function to find out.
