# Numpy -- Manipulation  
We can index through single-dimensioned numpy arrays the same way as with lists, using square brackets

In [3]:
import numpy as np 
my_array = np.array([1, 6, 3, 4])
print(my_array[0])
print(my_array[2])

1
3


More dimensions is different. Numpy arrays handle multiple dimensions in a single structure, rather than nesting lists inside of lists. We access the items in a 2d array using `[row, column]`

In [5]:
my_matrix = np.zeros((3, 4))
my_matrix[0, 0] = 1
print(my_matrix)

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
