# Lesson 11

# Execution Control

One of the fundamental aspects of a program is execution control.  By execution control we mean that the program can act in different ways depending on a **conditional statement**. <br>

Can you list some of the **conditions** that you have seen so far?

## Conditional Statements: `if`

Conditionals are statements that evaluate a **logical statement**, using the `if` statement, and then only execute a set of code if the condition evaluates as True. 

### Example 1: if with variables

In [1]:
condition = True

if condition:
    print('This code executes if the condition evaluates as True.')

This code executes if the condition evaluates as True.


In [2]:
# equivalent to above
if condition == True:
    print('This code executes if the condition evaluates as True.')

This code executes if the condition evaluates as True.


In [3]:
n = 1 
if n > 0:
    sign = 'positive'
print(sign)

positive


### Exercise 1: 

In [4]:
#What happens in the previous block of code if the value of n is 0? TRY IT! 
n = 0 
if n > 0:
    sign = 'positive'
print(sign)

positive


### Syntax notes 1

There are important pieces to the synatax 
* the logical statement leads with an `if` statement 
* the logical statement is followed by a colon `:`
* the code to be executed if the conditional statement is met is indented. 

Indentation facilitates clearly understanding of the hierarchy of execution control. 

### Table of Comparison Operations

A summary of the comparison operators and their equivalent **numpy function** is shown here:

| Operator	    | Equivalent ufunc    || Operator	   | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |


### Logical Operators 

The results of logical operations that can return a *single* value of **True** or **False** can also be used in execution control with an if statement.  <br>
Logical operations on arrays will often return Boolean arrays that contain the result of a comparison operator applied to each element of the array.   These can be combined in 
execution control by 

* **np.any** - check if any of the of elements of an array are True 
* **np.all** - check if all of the elements of an array are True


### Example 2: if with numpy arrays

In [5]:
import numpy as np 
array_a = np.array([-10, 22, 12, -1, 5, -6, 7, -9, 13], dtype = 'int')

In [6]:
if np.any(array_a < 0):                     # You can use any of the other operators too !=, ==, >= etc
    print('There were negative numbers')
    print(array_a)
    print(array_a < 0)


There were negative numbers
[-10  22  12  -1   5  -6   7  -9  13]
[ True False False  True False  True False  True False]


In [7]:
#what happens when the logical statement is false.  
if np.all(array_a < 0):
    print (array_a)
    print('All numbers were negative numbers')
print ("Moving on with code")

Moving on with code


## Conditional statements: `else`

After an if, you can use an `else` that will run if the logical statement was **False** and the conditional statement was not met. 

Only one of the code fragments will run.  The logical statement can only one of **True** or **False**

### Example 3: else with variables

In [8]:
condition = False

if condition:
    print('This code executes if the condition evaluates as True.')
else: 
    print('This code executes if the condition evaluates as False')

This code executes if the condition evaluates as False


### Example 4: else with numpy arrays

In [9]:
print (array_a)
if np.all(array_a < 0):
    print('All numbers were negative numbers')
else:
    print('At least one number was a positive number')
    

[-10  22  12  -1   5  -6   7  -9  13]
At least one number was a positive number


In [10]:
print(array_a)
if np.all(array_a < 0):
    print('All numbers were negative numbers')
else:
    print('At least one number was zero or a positive number')
    n_notnegative = np.sum(array_a >= 0)
    print('Not negative: ', n_notnegative)

[-10  22  12  -1   5  -6   7  -9  13]
At least one number was zero or a positive number
Not negative:  5


### Syntax notes 2

Notice that the `else` statement is itself a conditional statement.  Thus, it is completed with a colon `:`

Notice also, that the structure of an if-else statement can have multiple lines of code under each conditional statement 

    if logical statement: 
        do this  #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT IS TRUE 
        and this 
        and this 
    else:
        do this  #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT IS FALSE
        and this
        and this
    more code    #Will execute regardless of the logical statement being TRUE or FALSE
    and more code



## Conditional Statements: `elif`

Multiple **non-overlapping** conditional statements can be organized together using an `elif` statement.

`elif` combines else and if. 

### Example 5: elif with variables

In [11]:
condition_1 = False
condition_2 = True

if condition_1:
    print('This code executes if condition_1 evaluates as True.')
elif condition_2:
    print('This code executes if condition_1 did not evaluate as True, but condition_2 does.')
else: 
    print('This code executes if both condition_1 and condition_2 evaluate as False')

This code executes if condition_1 did not evaluate as True, but condition_2 does.


`elif` without an `else`

An `else` statement is not required, but if both the `if` and the `elif` condtions are not met (both evaluate as **False**), then nothing is returned.


In [12]:
condition_1 = False
condition_2 = False

if condition_1:
    print('This code executes if condition_1 evaluates as True.')
elif condition_2:
    print('This code executes if condition_1 did not evaluate as True, but condition_2 does.')

`elif` after an `else` does not make sense

The order will always be `if-elif-else`...with only the `if` being required. If the `elif` is at the end...it will never be tested, as the else will have already returned a value once reached (and thus Python will throw an error).


In [13]:
## THIS CODE WILL PRODUCE AN ERROR
condition_1 = False
condition_2 = False

if condition_1:
    print('This code executes if condition_1 evaluates as True.')
else: 
    print('This code executes if both condition_1 and condition_2 evaluate as False')
elif condition_2:
    print('This code executes if condition_1 did not evaluate as True, but condition_2 does.')

SyntaxError: invalid syntax (<ipython-input-13-aedfc0cec5db>, line 9)

In [14]:
math_ans = 20
if math_ans == 20:
    print("I did Math")
elif 1/0:
    print("I broke Math")
else:
    print("I didn't do math")

I did Math


### Exercise 2: 
Use the example above and try the exercises below.

In [15]:
#Change the conditions so that you will print "I broke Math". 
math_ans = 20
if math_ans != 20:
    print("I did Math")
elif 1:
    print("I broke Math")
else:
    print("I didn't do math")

I broke Math


In [16]:
# Change the conditions so that you will print "I didn't do Math"
math_ans = 20
if math_ans != 20:
    print("I did Math")
elif 0:
    print("I broke Math")
else:
    print("I didn't do math")

I didn't do math


### Python is an interpreted language.  It is not testing all your code before executing.  It is interpeting it line by line while executing it.  

### Syntax notes 3

    if logical statement 1: 
        do this  #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT 1 IS TRUE 
        and this 
        and this 
    elif logical statement 2: 
        do this  #CODE BLOCK EXECUTES ONLY IF LOGICAL STATMENT 2 is TRUE
        and this
        and this
    else:
        do this  #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT IS FALSE
        and this
        and this

An important implication of using the `if-elif-else` for execution control is to have a clear understanding of 
the relationship between logical statement 1 and logical statement 2.   

You should think about this in terms of sets and subsets.  There is a subset that meets the conditions of logical statement 1.  If that is **True** , *logical statement 2 is never evaluated* 

In [17]:
#This is a logically messed up set of statements. DONT DO THIS! 
n = 6
if n < 10:
    print('single digit')
elif n > 5:
    print('greater than 5')
else:
    print('double digit number')

single digit


The problem with the above block of code is that the subsets of the space of integers that meet the criterion overlap.  
* if n is 6,7,8,9 it meets two criteria, and only the first one executes. 
* if n >= 10 it meets two criteria and only the first one executes. 

### Example 6: elif with numpy arrays

In [18]:
print (array_a)
if np.any(array_a == 0):
    print ("There is atleast one element that is equal to zero")
elif np.all(array_a > 0):
    print ("All the elements are greater than zero")
else: 
    print ("There are positive and negative numbers in the array")

[-10  22  12  -1   5  -6   7  -9  13]
There are positive and negative numbers in the array


## Summary of properties of conditionals

- All conditionals start with an `if`, can have an optional and variable number of `elif`'s and an optional `else` statement
- Conditionals can take any expression that can be evaluated as `True` or `False`. 
- At most one component (`if` / `elif` / `else`) of a conditional will run
- The order of conditional blocks is always `if` then `elif`(s) then `else`
- Code is only ever executed if the condition is met

## Compound conditional statements 

The only requirement on the logical statement that makes the conditional `if` statement is that can return either **True** or **False**.  We can make compound conditional statements using Boolean Operators. 

### Table of Boolean Operators.

The following table summarizes the bitwise Boolean operators and their equivalent ufuncs:

| Operator	    | Equivalent ufunc    || Operator	    | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``&``          |``np.bitwise_and``   ||&#124;         |``np.bitwise_or``    |
|``^``          |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   |

<br>
### Example 7: compound conditions with variables

In [19]:
n = 8 
if (n%2 == 1) | (n > 10):
    print('Either odd or Larger than 10')
else:
    print('Even and less than or equal to 10')
    
#Note that the opposite of an OR (|) conditional boolean operator in an AND.     

Even and less than or equal to 10


In [20]:
n = 17 
if (n%2 == 0) & (n > 10):
    print('Even and Larger than 10')
else:
    print('Either odd or less than or equal to 10')
    
#Note that the opposite of an AND (&) conditional boolean operator in an OR.    

Either odd or less than or equal to 10


### Example 8: compound conditions with numpy arrays

In [21]:
print (array_a)
array_b = np.array([0, 12, 13, 5, 5, 6, -7, 10, 32], dtype = 'int')
print (array_b)

eq_gr_elements = np.bitwise_or(array_a == array_b, array_a > array_b)
if (eq_gr_elements.all()):
    print ("All the elements are equal or array_a is bigger than array_b")
elif (eq_gr_elements.any()): 
    print ("There is atleast one element in array_a that is equal to the corresponding element in array_b")
    print ("OR ")
    print ("There is an element in array_a that is greater than the corresponding element in array_b")
else: 
    print ("None of the elements are equal and array_a is not greater than array_b")
print(eq_gr_elements)

[-10  22  12  -1   5  -6   7  -9  13]
[ 0 12 13  5  5  6 -7 10 32]
There is atleast one element in array_a that is equal to the corresponding element in array_b
OR 
There is an element in array_a that is greater than the corresponding element in array_b
[False  True False False  True False  True False False]


### Exercise 3: 
Remember the example of the roller coaster ride? We are going to redo it now with **compound conditional** statements
Create a numpy array with the following information<br>
<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Height</th>
    </tr>
    <tr>
        <td>Justin</td>
        <td>65</td>
        <td>7</td>
    </tr>
    <tr>
        <td>Josh</td>
        <td>6</td>
        <td>6</td>
    </tr>
    <tr>
        <td>Aneya</td>
        <td>22</td>
        <td>5.5</td>
    </tr>
    <tr>
        <td>Eric</td>
        <td>18</td>
        <td>4.8</td>
    </tr>
    <tr>
        <td>Surekha</td>
        <td>81</td>
        <td>3</td>
    </tr>
    <tr>
        <td>Vikram</td>
        <td>100</td>
        <td>5.8</td>
    </tr>
</table>

The "Cube" roller coaster requires all those who get on the ride must be between 10 and 99 years old and at least 5 feet tall. 
You have to tell us which of the users can ride the roller coaster. <br>

Expected Output:<br>
`We have people who can get on the roller coaster.
Justin, Josh, Aneya, Eric, Surekha, Vikram
[ True False  True False False False]`

## Nested conditional statements 

Another option for execution control with combined conditions is to nest `if-elif-else` statements. 

This structure allows for more options in the output than the compount conditional statement. 

In [22]:
n = 17 
if n%2 == 0:   #Everything inside here is even
    if n > 10:
        print('Even and larger than 10')
    else:
        print('Even and smaller than or equal to 10')
else:         #Everything inside here is not even, i.e., odd.  
    if n > 10:
        print('Odd and larger than 10')
    else:
        print('Odd and smaller than or equal to 10')


Odd and larger than 10


Syntax notes 4

Notice that the else statement is itself a conditional statement. Thus, it is completed with a colon :

Notice also, that the structure of an if-else statement can have multiple lines of code under each conditional statement

    if logical statement 1: 
        if logical statement 2: #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT 1 AND LOGICAL STATEMENT 2 IS TRUE 
            do this  
            and this 
            and this
        else: #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT 1 IS TRUE AND LOGICAL STATEMENT 2 IS FALSE
            do this
            and this 
            and this 
    else:
        if logical statement 2: #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT 1 IS FALSE AND LOGICAL STATEMENT 2 IS TRUE 
            do this  
            and this 
            and this
        else: #CODE BLOCK EXECUTES ONLY IF LOGICAL STATEMENT 1 IS FALSE AND LOGICAL STATEMENT 2 IS FALSE
            do this
            and this 
            and this 


## Conditional Statements: Try-Except

The `try` conditional statement can be a useful statement in some scenarios where the quality of the input (or the user) is not under control. 

The fundamental organization of this `try-except` condtional statement mimics the `if-else` structure, except there is no logical statement. 

The execution will try to execute the code block inside the `try`.  If there is an execution error, it will run the code block in the `except`

This can be attractive when for example 200 subjects data in an experiment is being analyzed and there is potentially corruption in some of the data.   

In [23]:
try:
    g = 1/0
except:
    print('it failed')


it failed
